# Generated by Django 4.2.5 on 2023-09-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TypeBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_body_name", models.CharField(max_length=100)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.car"
                    ),
                ),
            ],
            options={
                "verbose_name": "Кузов",
                "verbose_name_plural": "Кузовы",
                "ordering": ["type_body_name"],
            },
        ),
    ]
